version: "3.8"

services:
    db:
        image: mariadb:10.6
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_db
            MYSQL_USER: todo_user
            MYSQL_PASSWORD: todo_password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    php-apache:
        build: .
        container_name: todo-app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        depends_on:
            - db

volumes:
    db_data:
